sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - 'if [ ! $(type -P pipenvv) ]; then pip install pipenv; fi'
  - 'pipenv install --dev'
script: cd validator && pipenv run pytest
notification:
  email:
    on_success: never
    on_failure: change
    on_pull_request: false
