sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r validator/requirements.txt
  - pip install -r validator/requirements-dev.txt
script: cd validator && py.test
notification:
  email:
    on_success: never
    on_failure: change
    on_pull_request: false
