[package]
name = "spacedirectory-validator-service"
version = "0.1.0"
authors = ["Stefan Schindler <dns2utf8@estada.ch>"]

[dependencies]
nickel = "0.9"
rustc-serialize = "0.3"
url = "1.0"
spaceapi-validator = { path = "../validator" }
